### ISSUE TITLE
Typo in Readme

### ISSUE THREAD

**Issue by hedonistrh** [collinb9/understatAPI#9]
In the readme, it says following for git related cloning

```bash
git clone git@github.com:collinb9/understatAPI understatAPI
```

I am using https one but for git one, i think it should be following for git one.
```bash
git clone git@github.com:collinb9/understatAPI.git
```

**Comment by hedonistrh** [comment]
In addition to that, I also think there is no setup.py in the current version of the repo so following won't work. 🤔 
```shell
python setup.py install
```

**Comment by collinb9** [comment]
Yeah good catch, thanks. I recently switched from setup.py to pyproject.toml & setup.cfg, forgot to fix the readme

**Comment by collinb9** [comment]
I think the line about cloning the repo is fine, but I've updated the installation instructions. Closing this issue now
